# Generated by Django 4.1.3 on 2022-12-29 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('discount_status', models.CharField(choices=[('b', 'Bronze'), ('s', 'Silver'), ('g', 'Gold')], default='b', max_length=1)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('verification', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'permissions': (('can_verificate', 'Может верифицировать'),),
            },
        ),
    ]
