# Generated by Django 4.1.3 on 2022-12-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
