# Generated by Django 4.1.3 on 2023-03-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_remove_profile_email_remove_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=10)),
                ('price_multiplier', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
