# Generated by Django 4.1.3 on 2023-03-14 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='discount_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_user.discount'),
            preserve_default=False,
        ),
    ]
