# Generated by Django 4.1.3 on 2023-01-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
