# Generated by Django 4.1.3 on 2023-03-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_basket', '0002_delete_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('house', models.CharField(max_length=10)),
                ('housing', models.IntegerField()),
                ('apartment', models.IntegerField()),
            ],
        ),
    ]
