# Generated by Django 4.1.3 on 2022-12-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=20, verbose_name='Производитель')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='цена')),
                ('vendor', models.CharField(blank=True, max_length=50, verbose_name='Вендор')),
                ('image', models.ImageField(height_field=300, upload_to='videostore_project/media/', verbose_name='Изображение', width_field=300)),
            ],
        ),
    ]
