# Generated by Django 4.1.3 on 2023-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=20, verbose_name='Производитель')),
                ('price', models.IntegerField(null=True, verbose_name='цена')),
                ('vendor', models.CharField(blank=True, max_length=50, verbose_name='Вендор')),
                ('promo_type', models.CharField(choices=[('n', 'new'), ('r', 'regular')], default='r', max_length=10)),
                ('promo_note', models.CharField(blank=True, max_length=300, verbose_name='Промо-текст')),
                ('image', models.FilePathField(blank=True, path='media/', verbose_name='Изображение')),
                ('image_big', models.FilePathField(blank=True, path='media/', verbose_name='Изображение большое')),
                ('background', models.FilePathField(blank=True, path='media/', verbose_name='Фон')),
            ],
        ),
    ]
