# Generated by Django 4.1.3 on 2022-12-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_alter_videocard_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocard',
            name='price',
            field=models.FloatField(null=True, verbose_name='цена'),
        ),
    ]
