# Generated by Django 4.1.3 on 2023-01-07 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_videocardinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='info',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app_main.videocardinfo'),
            preserve_default=False,
        ),
    ]
