# Generated by Django 4.1.3 on 2023-01-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_videocard_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocardinfo',
            name='cooling_width',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocardinfo',
            name='core_count',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocardinfo',
            name='core_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='videocardinfo',
            name='height',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocardinfo',
            name='interface',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='videocardinfo',
            name='length',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocardinfo',
            name='memory_band_width',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocardinfo',
            name='memory_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='videocardinfo',
            name='memory_volume',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocardinfo',
            name='recommended_energy_supply',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
