# Generated by Django 4.1.3 on 2023-01-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_videocardinfo_cooling_width_videocardinfo_core_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocardinfo',
            name='power_slots',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videocardinfo',
            name='core_frequency',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='videocardinfo',
            name='memory_frequency',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='videocardinfo',
            name='memory_volume',
            field=models.IntegerField(blank=True),
        ),
    ]
