# Generated by Django 4.1.3 on 2023-01-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_videocardinfo_power_slots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocardinfo',
            name='cooling_width',
        ),
        migrations.RemoveField(
            model_name='videocardinfo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='videocardinfo',
            name='length',
        ),
        migrations.RemoveField(
            model_name='videocardinfo',
            name='power_slots',
        ),
    ]
