# Generated by Django 4.1.3 on 2022-12-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_alter_videocard_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocard',
            name='image',
            field=models.ImageField(upload_to='videostore_project/media/', verbose_name='Изображение'),
        ),
    ]
