# Generated by Django 4.1.3 on 2022-12-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_alter_videocard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='image_upload',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Загрузка изображения'),
        ),
    ]
