# Generated by Django 4.1.3 on 2022-12-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0010_videocard_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocard',
            name='image_upload',
            field=models.ImageField(blank=True, height_field=500, upload_to='media/', verbose_name='Загрузка изображения', width_field=500),
        ),
    ]
