# Generated by Django 4.1.3 on 2022-12-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_alter_videocard_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='background',
            field=models.FilePathField(blank=True, path='media/', verbose_name='Фон'),
        ),
        migrations.AddField(
            model_name='videocard',
            name='image_big',
            field=models.FilePathField(blank=True, path='media/', verbose_name='Изображение большое'),
        ),
    ]
