# Generated by Django 4.1.3 on 2022-12-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_videocard_background_videocard_image_big'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='image_big_upload',
            field=models.ImageField(blank=True, height_field=1500, upload_to='media/', verbose_name='Загрузка большого изображения', width_field=1500),
        ),
    ]
