# Generated by Django 4.1.3 on 2022-12-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0015_remove_videocard_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='promo_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='Промо-текст'),
        ),
    ]
