# Generated by Django 4.1.3 on 2022-12-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0016_videocard_promo_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocard',
            name='price',
            field=models.IntegerField(null=True, verbose_name='цена'),
        ),
    ]
