# Generated by Django 4.1.3 on 2022-12-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0017_alter_videocard_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='promo_type',
            field=models.CharField(choices=[('n', 'new'), ('r', 'regular')], default='r', max_length=10),
        ),
    ]
